# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute the app, save build artifacts, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/xcode

pool:
  vmImage: 'macOS 10.13'

variables:
  scheme: 'myCurrencyExchange'
  sdk: 'iphoneos'
  configuration: 'Debug'
  GITHUB_ACCESS_TOKEN: '348178f011f66cf7174c0abe3bede91a023cec84'
  
steps:
- script: curl https://api.github.com/rate_limit
  displayName: 'Unauthenticated rate limit'
- script: echo $(System.AccessToken)
  displayName: 'Print Token'
  env:
    SYSTEM_ACCESSTOKEN: '348178f011f66cf7174c0abe3bede91a023cec84'
- script: curl https://api.github.com/rate_limit?access_token=0fdeca3269c550763ad9d14a7541afa2541d8bbd
  displayName: 'Authenticated rate limit'
- script: /usr/local/bin/carthage update --platform ios
  displayName: 'Carthage installation'
  env:
    GITHUB_ACCESS_TOKEN: '348178f011f66cf7174c0abe3bede91a023cec84'
- task: Xcode@5
  displayName: 'Running XCTest/XCUITest'
  inputs:
    actions: 'test'
    scheme: '$(scheme)'
    sdk: 'iphonesimulator'
    configuration: '$(configuration)'
    xcodeVersion: 'default' # Options: 8, 9, default, specifyPath
    packageApp: false
    xcWorkspacePath: 'myCurrencyExchange.xcodeproj'
    destinationSimulators: 'iPhone 7'
    destinationTypeOption: 'simulators'
    destinationPlatformOption: 'iOS'
    signingOption: "auto"
    useXcpretty: true
    publishJUnitResults: 'build/reports/junit.xml'
- task: Xcode@5
  displayName: 'Xcode debug build'
  inputs:
    actions: 'build'
    scheme: '$(scheme)'
    sdk: '$(sdk)'
    configuration: '$(configuration)'
    xcodeVersion: 'default'
    packageApp: false
    xcWorkspacePath: 'myCurrencyExchange.xcodeproj'
    useXcpretty: true
