# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute the app, save build artifacts, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/xcode

pool:
  vmImage: 'macOS 10.13'

variables:
  scheme: 'myCurrencyExchange'
  sdk: 'iphoneos'
  configuration: 'Debug'
  
steps:
- script: curl https://api.github.com/rate_limit
  displayName: 'Unauthenticated rate limit'
#- script: /usr/local/bin/carthage update --platform ios
- bash : chmod +x get_token.sh
  displayName: 'Modify permission'
- bash : ./get_token.sh
  displayName: 'Create token'
- task: CopyFiles@2
  displayName: 'Copy token files'
  inputs:
    SourceFolder: $(Build.SourcesDirectory)
    Contents: '*.txt'
    TargetFolder: $(build.artifactstagingdirectory)/Token
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: token'
- bash: GITHUB_ACCESS_TOKEN=$(<token.txt) carthage bootstrap --platform ios
  env:
    $GITHUB_ACCESS_TOKEN: ''
  displayName: 'Carthage installation'
- task: Xcode@5
  displayName: 'Running XCTest/XCUITest'
  inputs:
    actions: 'test'
    scheme: '$(scheme)'
    sdk: 'iphonesimulator'
    configuration: '$(configuration)'
    xcodeVersion: 'default' # Options: 8, 9, default, specifyPath
    packageApp: false
    xcWorkspacePath: 'myCurrencyExchange.xcodeproj'
    destinationSimulators: 'iPhone 7'
    destinationTypeOption: 'simulators'
    destinationPlatformOption: 'iOS'
    signingOption: "auto"
    useXcpretty: true
    publishJUnitResults: 'build/reports/junit.xml'
# Publish test results to Azure Pipelines
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit' # Options: JUnit, NUnit, VSTest, xUnit, cTest
    testResultsFiles: 'build/reports/junit.xml' 
- task: Xcode@5
  displayName: 'Xcode debug build'
  inputs:
    actions: 'build'
    scheme: '$(scheme)'
    sdk: '$(sdk)'
    configuration: '$(configuration)'
    xcodeVersion: 'default'
    packageApp: false
    xcWorkspacePath: 'myCurrencyExchange.xcodeproj'
    useXcpretty: true
