# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute the app, save build artifacts, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/xcode

pool:
  vmImage: 'macOS 10.13'

variables:
  scheme: 'myCurrencyExchange'
  sdk: 'iphoneos'
  configuration: 'Debug'
  GITHUB_ACCESS_TOKEN: 'bb1f9c9c9bbd5fd9c81bf08b1dca9f1b3b3c9779'
  
steps:
- script: curl https://api.github.com/rate_limit
  displayName: 'Unauthenticated rate limit'
- script: /usr/local/bin/carthage update --platform ios
  displayName: 'Carthage installation'
- task: Xcode@5
  displayName: 'Running XCTest/XCUITest'
  inputs:
    actions: 'test'
    scheme: '$(scheme)'
    sdk: 'iphonesimulator'
    configuration: '$(configuration)'
    xcodeVersion: 'default' # Options: 8, 9, default, specifyPath
    packageApp: false
    xcWorkspacePath: 'myCurrencyExchange.xcodeproj'
    destinationSimulators: 'iPhone 7'
    destinationTypeOption: 'simulators'
    destinationPlatformOption: 'iOS'
    signingOption: "auto"
    useXcpretty: true
    publishJUnitResults: 'build/reports/junit.xml'
- task: Xcode@5
  displayName: 'Xcode debug build'
  inputs:
    actions: 'build'
    scheme: '$(scheme)'
    sdk: '$(sdk)'
    configuration: '$(configuration)'
    xcodeVersion: 'default'
    packageApp: false
    xcWorkspacePath: 'myCurrencyExchange.xcodeproj'
    useXcpretty: true
